/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef BAT_REVISION_H
#define BAT_REVISION_H

#define BAT_REVISION "git commit d9be15f on 2018-03-13"
#define BAT_VERSION "d9be15f"

#endif // BAT_REVISION_H
